### ISSUE TITLE
Repository Empty

### ISSUE THREAD

**Issue by avi-amalanshu** [NeuromorphicComputing/SoftHebb#1]
Hello, I would like to reproduce some results from the paper, but the code used to generate them is unavailable on the repository. The paper is quite fascinating and the methodology has scope for widespread application if the potency is shown to be reproducible.

**Comment by imanehmz** [comment]
Hello, they've said that they will make the code available soon

**Comment by tmoraitis** [comment]
Indeed we will. Thank you both.

**Comment by tmoraitis** [comment]
Hi both. We have now uploaded the code. Thanks for your patience.
